//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-11-22 16:04:00
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace ZhongYan.DingCan.Entities
{    
    /// <summary>
    /// 
    /// </summary>    
	public class DingCan_Menu
    {
        
		/// <summary>
        /// 
        /// </summary>        
        public DateTime riqi { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string ZA { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string ZB { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string ZC { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string ZD { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string WA { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string WB { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string WC { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string WD { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string Y { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public int ID { get; set; }
    }
}
