//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-11-22 16:04:00
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace ZhongYan.DingCan.Entities
{    
    /// <summary>
    /// 
    /// </summary>    
	public class DingCan_JiaGe
    {
        
		/// <summary>
        /// Z:wuCan,W:WanCan;Y:YeCan
        /// </summary>        
        public string WuWanYe { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string CanLei { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public int? JiaGe { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public int ID { get; set; }
    }
}
