//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-11-22 16:04:00
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace ZhongYan.DingCan.Entities
{    
    /// <summary>
    /// 
    /// </summary>    
	public class DingCan_Person
    {
        
		/// <summary>
        /// SAP 编号
        /// </summary>        
        public string SAP_BH { get; set; }
    
		/// <summary>
        /// 工作正编号
        /// </summary>        
        public string GZZ_BH { get; set; }
    
		/// <summary>
        /// 统一身份帐号
        /// </summary>        
        public string UID { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string XingMing { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string company { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string DanWei { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string BuMen { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string RYZ { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string RYZZ { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string GangWei { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string Station_name { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string ShouQuan { get; set; }
    
		/// <summary>
        /// 系统维护
        /// </summary>        
        public string XiTongWeiHu { get; set; }
    
		/// <summary>
        /// 线路维护
        /// </summary>        
        public string XianLuWeiHu { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string ShouQuanWeiHu { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string YongCanDiDianWeiHu { get; set; }
    
		/// <summary>
        /// 统计权限
        /// </summary>        
        public string TongJi { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string MenuWeiHu { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public decimal? KeYongCiShu { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string AccountNo { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string MinZu { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public string Disable { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public int? CardNo { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public decimal? KeYongFenShu { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public short? Identi { get; set; }
    
		/// <summary>
        /// 
        /// </summary>        
        public int? Condition { get; set; }
    }
}
