//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-10-26 15:54:04
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace AdminApp.Base.Entities
{    
    /// <summary>
    /// 
    /// </summary>    
	public class Organization
    {
        
		/// <summary>
        /// 
        /// </summary>        
        public string Id { get; set; }
    
		/// <summary>
        /// 组织机构名称
        /// </summary>        
        public string Name { get; set; }
    
		/// <summary>
        /// 内部名称
        /// </summary>        
        public string InnerName { get; set; }
    
		/// <summary>
        /// 内部编码
        /// </summary>        
        public string InnerCode { get; set; }
    
		/// <summary>
        /// 标准编码
        /// </summary>        
        public string StandardCode { get; set; }
    
		/// <summary>
        /// 上级组织机构ID
        /// </summary>        
        public string ParentId { get; set; }
    
		/// <summary>
        /// 有效性
        /// </summary>        
        public int InUse { get; set; }
    }
}
